/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern void stub_GLBluetooth_init_0(jmethodID id, va_list args);
extern jboolean stub_GLBluetooth_isSupported_1(jmethodID id, va_list args);
extern jboolean stub_GLBluetooth_isAvailable_2(jmethodID id, va_list args);
extern void stub_GLBluetooth_setAvailable_3(jmethodID id, va_list args);
extern jboolean stub_GLBluetooth_create_4(jmethodID id, va_list args);
extern jobject stub_GLBluetooth_getDisplayName_5(jmethodID id, va_list args);
extern void stub_GLBluetooth_destroy_6(jmethodID id, va_list args);
extern void stub_GLBluetooth_connect_7(jmethodID id, va_list args);
extern void stub_GLBluetooth_send_8(jmethodID id, va_list args);
extern jboolean stub_GLBluetooth_acceptConnection_9(jmethodID id, va_list args);
extern void stub_GLBluetooth_denyConnection_10(jmethodID id, va_list args);
extern jobject stub_GLBluetooth_getReceiveData_11(jmethodID id, va_list args);
extern jobject stub_GLBluetoothService_GLBluetoothService_12(jmethodID id, va_list args);
extern void stub_GLBluetoothService_Update_13(jmethodID id, va_list args);
extern jboolean stub_GLBluetoothService_startListen_14(jmethodID id, va_list args);
extern void stub_GLBluetoothService_enableDiscovery_15(jmethodID id, va_list args);
extern jboolean stub_GLBluetoothService_startDiscovery_16(jmethodID id, va_list args);
extern void stub_GLBluetoothService_stopDiscovery_17(jmethodID id, va_list args);
extern void stub_GLBluetoothService_close_18(jmethodID id, va_list args);
extern void stub_GLBluetoothService_connect_19(jmethodID id, va_list args);
extern void stub_GLBluetoothService_send_20(jmethodID id, va_list args);
extern jint stub_GLBluetoothService_convertMacAddressToInteger_21(jmethodID id, va_list args);
extern jobject stub_GLBluetoothService_getDisplayName_22(jmethodID id, va_list args);
extern void stub_GLBluetoothService_connectionFailed_23(jmethodID id, va_list args);
extern void stub_GLBluetoothService_connectionLost_24(jmethodID id, va_list args);
extern void stub_GLBluetoothService_connected_25(jmethodID id, va_list args);
extern void stub_GLBluetoothService_acceptConnection_26(jmethodID id, va_list args);
extern void stub_GLBluetoothService_denyConnection_27(jmethodID id, va_list args);
extern jobject stub_GLBluetoothService_getReceiveData_28(jmethodID id, va_list args);
extern void stub_GLBluetoothService_parseIncommingData_29(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_30(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_restoreMasterVolume_31(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_32(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoaded_33(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoadedBig_34(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_35(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_36(jmethodID id, va_list args);
extern jobject stub_GLMediaPlayer_getSoundFile_37(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSoundBig_38(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSoundBig_39(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSound_40(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_releaseIdleMediaPlayers_41(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSoundBig_42(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_GetDeviceSoundType_43(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSound_44(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSoundBig_45(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSound_46(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSoundBig_47(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSound_48(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSoundForce_49(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSoundBig_50(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSound_51(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSoundBig_52(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolume_53(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolumeBig_54(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resetSound_55(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setPitch_56(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllSounds_57(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllPool_58(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllBig_59(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllSounds_60(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeAllSounds_61(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_destroySoundPool_62(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_loadMovie_63(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_ResumeMovie_64(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setMusicGain_65(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setSfxGain_66(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVfxGain_67(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isMediaPlaying_68(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_releaseSoundPool_69(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_initSoundPoolArray_70(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_detectPhoneLang_71(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_BlockSounds_72(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_getDeviceWidth_73(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_GetDeviceType_74(jmethodID id, va_list args);
extern void stub_GLResLoader_init_75(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLength_76(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_77(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_78(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getRawResource_79(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceBytes_80(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getString_81(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceOpen_82(jmethodID id, va_list args);
extern jint stub_GLResLoader_copyResourceFromAssets_83(jmethodID id, va_list args);
extern jobject stub_GLResLoader_copyMovieFileFromAssetsToTMP_84(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLength2_85(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceRead_86(jmethodID id, va_list args);
extern jbyte stub_GLResLoader_getResourceReadByte_87(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceSkip_88(jmethodID id, va_list args);
extern void stub_GLResLoader_getResourceClose_89(jmethodID id, va_list args);
extern jobject stub_GameGLSurfaceView_GameGLSurfaceView_90(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onWindowFocusChanged_91(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onSizeChanged_92(jmethodID id, va_list args);
extern jboolean stub_GameGLSurfaceView_onTouchEvent_93(jmethodID id, va_list args);
extern jobject stub_GameRenderer_GameRenderer_94(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceCreated_95(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceChanged_96(jmethodID id, va_list args);
extern void stub_GameRenderer_onDrawFrame_97(jmethodID id, va_list args);
extern void stub_Gangster2_onCreate_98(jmethodID id, va_list args);
extern void stub_Gangster2_loadConfig_99(jmethodID id, va_list args);
extern void stub_Gangster2_onPause_100(jmethodID id, va_list args);
extern void stub_Gangster2_onResume_101(jmethodID id, va_list args);
extern void stub_Gangster2_onStop_102(jmethodID id, va_list args);
extern void stub_Gangster2_onDestroy_103(jmethodID id, va_list args);
extern jboolean stub_Gangster2_isDemo_104(jmethodID id, va_list args);
extern void stub_Gangster2_onRestart_105(jmethodID id, va_list args);
extern void stub_Gangster2_onStart_106(jmethodID id, va_list args);
extern jboolean stub_Gangster2_onTrackballEvent_107(jmethodID id, va_list args);
extern jboolean stub_Gangster2_onKeyDown_108(jmethodID id, va_list args);
extern jboolean stub_Gangster2_onKeyUp_109(jmethodID id, va_list args);
extern void stub_Gangster2_sendAppToBackground_110(jmethodID id, va_list args);
extern void stub_Gangster2_Exit_111(jmethodID id, va_list args);
extern void stub_Gangster2_onActivityResult_112(jmethodID id, va_list args);
extern jint stub_Gangster2_isWifiAlive_113(jmethodID id, va_list args);
extern jint stub_Gangster2_unlockDemo_114(jmethodID id, va_list args);
extern void stub_Gangster2_lockDemo_115(jmethodID id, va_list args);
extern void stub_Gangster2_IncreaseLaunchTimes_116(jmethodID id, va_list args);
extern jint stub_Gangster2_DisableLaunchGame_117(jmethodID id, va_list args);
extern void stub_Gangster2_openBrowser_118(jmethodID id, va_list args);
extern void stub_Gangster2_OpenGLive_119(jmethodID id, va_list args);
extern void stub_Gangster2_NotifyTrophy_120(jmethodID id, va_list args);
extern void stub_Gangster2_readFromFile_121(jmethodID id, va_list args);
extern void stub_Gangster2_initialize_Trophy_122(jmethodID id, va_list args);
extern void stub_Gangster2_VZRestoreNetworkState_123(jmethodID id, va_list args);
extern void stub_Gangster2_VZInitMobileNetwork_124(jmethodID id, va_list args);
extern jint stub_Gangster2_VZIsMobileNetworkReady_125(jmethodID id, va_list args);
extern void stub_Gangster2_VZRequestLogin_126(jmethodID id, va_list args);
extern void stub_Gangster2_VZRequestPurchaseGame_127(jmethodID id, va_list args);
extern jint stub_Gangster2_VZIsInProgress_128(jmethodID id, va_list args);
extern jint stub_Gangster2_VZIsErrorOcurred_129(jmethodID id, va_list args);
extern jobject stub_Gangster2_VZGetGamePrice_130(jmethodID id, va_list args);
extern jobject stub_Gangster2_VZGetGameName_131(jmethodID id, va_list args);
extern jobject stub_Gangster2_VZGetLastServerMsg_132(jmethodID id, va_list args);
extern void stub_Gangster2_onSensorChanged_133(jmethodID id, va_list args);
extern void stub_Gangster2_onAccuracyChanged_134(jmethodID id, va_list args);
extern void stub_MyVideoView_onCreate_135(jmethodID id, va_list args);
extern void stub_MyVideoView_onPause_136(jmethodID id, va_list args);
extern void stub_MyVideoView_onStop_137(jmethodID id, va_list args);
extern void stub_MyVideoView_onWindowFocusChanged_138(jmethodID id, va_list args);
extern void stub_MyVideoView_sendAppToBackground_139(jmethodID id, va_list args);
extern jboolean stub_MyVideoView_onKeyUp_140(jmethodID id, va_list args);
extern jboolean stub_MyVideoView_onKeyDown_141(jmethodID id, va_list args);
extern jboolean stub_MyVideoView_onKeyLongPress_142(jmethodID id, va_list args);
extern void stub_MyVideoView_playVideo_143(jmethodID id, va_list args);
extern jboolean stub_MyVideoView_onTouchEvent_144(jmethodID id, va_list args);
extern void stub_MyVideoView_HideButton_145(jmethodID id, va_list args);
extern void stub_MyVideoView_ShowButton_146(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "init", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 1, "isSupported", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 2, "isAvailable", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 3, "setAvailable", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 4, "create", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 5, "getDisplayName", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 6, "destroy", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 7, "connect", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 8, "send", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 9, "acceptConnection", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 10, "denyConnection", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 11, "getReceiveData", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth
    { 12, "GLBluetoothService", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 13, "Update", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 14, "startListen", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 15, "enableDiscovery", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 16, "startDiscovery", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 17, "stopDiscovery", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 18, "close", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 19, "connect", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 20, "send", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 21, "convertMacAddressToInteger", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 22, "getDisplayName", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 23, "connectionFailed", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 24, "connectionLost", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 25, "connected", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 26, "acceptConnection", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 27, "denyConnection", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 28, "getReceiveData", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 29, "parseIncommingData", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService
    { 30, "init", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 31, "restoreMasterVolume", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 32, "init", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 33, "isSoundLoaded", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 34, "isSoundLoadedBig", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 35, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 36, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 37, "getSoundFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 38, "loadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 39, "loadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 40, "playSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 41, "releaseIdleMediaPlayers", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 42, "playSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 43, "GetDeviceSoundType", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 44, "pauseSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 45, "pauseSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 46, "resumeSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 47, "resumeSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 48, "stopSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 49, "stopSoundForce", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 50, "stopSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 51, "unloadSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 52, "unloadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 53, "setVolume", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 54, "setVolumeBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 55, "resetSound", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 56, "setPitch", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 57, "stopAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 58, "stopAllPool", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 59, "stopAllBig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 60, "pauseAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 61, "resumeAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 62, "destroySoundPool", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 63, "loadMovie", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 64, "ResumeMovie", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 65, "setMusicGain", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 66, "setSfxGain", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 67, "setVfxGain", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 68, "isMediaPlaying", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 69, "releaseSoundPool", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 70, "initSoundPoolArray", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 71, "detectPhoneLang", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 72, "BlockSounds", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 73, "getDeviceWidth", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 74, "GetDeviceType", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer
    { 75, "init", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 76, "getResourceLength", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 77, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 78, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 79, "getRawResource", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 80, "getResourceBytes", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 81, "getString", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 82, "getResourceOpen", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 83, "copyResourceFromAssets", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 84, "copyMovieFileFromAssetsToTMP", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 85, "getResourceLength2", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 86, "getResourceRead", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 87, "getResourceReadByte", METHOD_TYPE_BYTE },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 88, "getResourceSkip", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 89, "getResourceClose", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader
    { 90, "GameGLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView
    { 91, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView
    { 92, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView
    { 93, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView
    { 94, "GameRenderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer
    { 95, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer
    { 96, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer
    { 97, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer
    { 98, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 99, "loadConfig", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 100, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 101, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 102, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 103, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 104, "isDemo", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 105, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 106, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 107, "onTrackballEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 108, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 109, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 110, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 111, "Exit", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 112, "onActivityResult", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 113, "isWifiAlive", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 114, "unlockDemo", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 115, "lockDemo", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 116, "IncreaseLaunchTimes", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 117, "DisableLaunchGame", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 118, "openBrowser", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 119, "OpenGLive", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 120, "NotifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 121, "readFromFile", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 122, "initialize_Trophy", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 123, "VZRestoreNetworkState", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 124, "VZInitMobileNetwork", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 125, "VZIsMobileNetworkReady", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 126, "VZRequestLogin", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 127, "VZRequestPurchaseGame", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 128, "VZIsInProgress", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 129, "VZIsErrorOcurred", METHOD_TYPE_INT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 130, "VZGetGamePrice", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 131, "VZGetGameName", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 132, "VZGetLastServerMsg", METHOD_TYPE_OBJECT },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 133, "onSensorChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 134, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2
    { 135, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 136, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 137, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 138, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 139, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 140, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 141, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 142, "onKeyLongPress", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 143, "playVideo", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 144, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 145, "HideButton", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
    { 146, "ShowButton", METHOD_TYPE_VOID },  // com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 0, stub_GLBluetooth_init_0 },
    { 3, stub_GLBluetooth_setAvailable_3 },
    { 6, stub_GLBluetooth_destroy_6 },
    { 7, stub_GLBluetooth_connect_7 },
    { 8, stub_GLBluetooth_send_8 },
    { 10, stub_GLBluetooth_denyConnection_10 },
    { 13, stub_GLBluetoothService_Update_13 },
    { 15, stub_GLBluetoothService_enableDiscovery_15 },
    { 17, stub_GLBluetoothService_stopDiscovery_17 },
    { 18, stub_GLBluetoothService_close_18 },
    { 19, stub_GLBluetoothService_connect_19 },
    { 20, stub_GLBluetoothService_send_20 },
    { 23, stub_GLBluetoothService_connectionFailed_23 },
    { 24, stub_GLBluetoothService_connectionLost_24 },
    { 25, stub_GLBluetoothService_connected_25 },
    { 26, stub_GLBluetoothService_acceptConnection_26 },
    { 27, stub_GLBluetoothService_denyConnection_27 },
    { 29, stub_GLBluetoothService_parseIncommingData_29 },
    { 30, stub_GLMediaPlayer_init_30 },
    { 31, stub_GLMediaPlayer_restoreMasterVolume_31 },
    { 32, stub_GLMediaPlayer_init_32 },
    { 35, stub_GLMediaPlayer_loadSound_35 },
    { 36, stub_GLMediaPlayer_loadSound_36 },
    { 38, stub_GLMediaPlayer_loadSoundBig_38 },
    { 39, stub_GLMediaPlayer_loadSoundBig_39 },
    { 40, stub_GLMediaPlayer_playSound_40 },
    { 41, stub_GLMediaPlayer_releaseIdleMediaPlayers_41 },
    { 42, stub_GLMediaPlayer_playSoundBig_42 },
    { 44, stub_GLMediaPlayer_pauseSound_44 },
    { 45, stub_GLMediaPlayer_pauseSoundBig_45 },
    { 46, stub_GLMediaPlayer_resumeSound_46 },
    { 47, stub_GLMediaPlayer_resumeSoundBig_47 },
    { 48, stub_GLMediaPlayer_stopSound_48 },
    { 49, stub_GLMediaPlayer_stopSoundForce_49 },
    { 50, stub_GLMediaPlayer_stopSoundBig_50 },
    { 51, stub_GLMediaPlayer_unloadSound_51 },
    { 52, stub_GLMediaPlayer_unloadSoundBig_52 },
    { 53, stub_GLMediaPlayer_setVolume_53 },
    { 54, stub_GLMediaPlayer_setVolumeBig_54 },
    { 55, stub_GLMediaPlayer_resetSound_55 },
    { 56, stub_GLMediaPlayer_setPitch_56 },
    { 57, stub_GLMediaPlayer_stopAllSounds_57 },
    { 58, stub_GLMediaPlayer_stopAllPool_58 },
    { 59, stub_GLMediaPlayer_stopAllBig_59 },
    { 60, stub_GLMediaPlayer_pauseAllSounds_60 },
    { 61, stub_GLMediaPlayer_resumeAllSounds_61 },
    { 62, stub_GLMediaPlayer_destroySoundPool_62 },
    { 64, stub_GLMediaPlayer_ResumeMovie_64 },
    { 65, stub_GLMediaPlayer_setMusicGain_65 },
    { 66, stub_GLMediaPlayer_setSfxGain_66 },
    { 67, stub_GLMediaPlayer_setVfxGain_67 },
    { 69, stub_GLMediaPlayer_releaseSoundPool_69 },
    { 70, stub_GLMediaPlayer_initSoundPoolArray_70 },
    { 72, stub_GLMediaPlayer_BlockSounds_72 },
    { 75, stub_GLResLoader_init_75 },
    { 89, stub_GLResLoader_getResourceClose_89 },
    { 91, stub_GameGLSurfaceView_onWindowFocusChanged_91 },
    { 92, stub_GameGLSurfaceView_onSizeChanged_92 },
    { 95, stub_GameRenderer_onSurfaceCreated_95 },
    { 96, stub_GameRenderer_onSurfaceChanged_96 },
    { 97, stub_GameRenderer_onDrawFrame_97 },
    { 98, stub_Gangster2_onCreate_98 },
    { 99, stub_Gangster2_loadConfig_99 },
    { 100, stub_Gangster2_onPause_100 },
    { 101, stub_Gangster2_onResume_101 },
    { 102, stub_Gangster2_onStop_102 },
    { 103, stub_Gangster2_onDestroy_103 },
    { 105, stub_Gangster2_onRestart_105 },
    { 106, stub_Gangster2_onStart_106 },
    { 110, stub_Gangster2_sendAppToBackground_110 },
    { 111, stub_Gangster2_Exit_111 },
    { 112, stub_Gangster2_onActivityResult_112 },
    { 115, stub_Gangster2_lockDemo_115 },
    { 116, stub_Gangster2_IncreaseLaunchTimes_116 },
    { 118, stub_Gangster2_openBrowser_118 },
    { 119, stub_Gangster2_OpenGLive_119 },
    { 120, stub_Gangster2_NotifyTrophy_120 },
    { 121, stub_Gangster2_readFromFile_121 },
    { 122, stub_Gangster2_initialize_Trophy_122 },
    { 123, stub_Gangster2_VZRestoreNetworkState_123 },
    { 124, stub_Gangster2_VZInitMobileNetwork_124 },
    { 126, stub_Gangster2_VZRequestLogin_126 },
    { 127, stub_Gangster2_VZRequestPurchaseGame_127 },
    { 133, stub_Gangster2_onSensorChanged_133 },
    { 134, stub_Gangster2_onAccuracyChanged_134 },
    { 135, stub_MyVideoView_onCreate_135 },
    { 136, stub_MyVideoView_onPause_136 },
    { 137, stub_MyVideoView_onStop_137 },
    { 138, stub_MyVideoView_onWindowFocusChanged_138 },
    { 139, stub_MyVideoView_sendAppToBackground_139 },
    { 143, stub_MyVideoView_playVideo_143 },
    { 145, stub_MyVideoView_HideButton_145 },
    { 146, stub_MyVideoView_ShowButton_146 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 1, stub_GLBluetooth_isSupported_1 },
    { 2, stub_GLBluetooth_isAvailable_2 },
    { 4, stub_GLBluetooth_create_4 },
    { 9, stub_GLBluetooth_acceptConnection_9 },
    { 14, stub_GLBluetoothService_startListen_14 },
    { 16, stub_GLBluetoothService_startDiscovery_16 },
    { 93, stub_GameGLSurfaceView_onTouchEvent_93 },
    { 104, stub_Gangster2_isDemo_104 },
    { 107, stub_Gangster2_onTrackballEvent_107 },
    { 108, stub_Gangster2_onKeyDown_108 },
    { 109, stub_Gangster2_onKeyUp_109 },
    { 140, stub_MyVideoView_onKeyUp_140 },
    { 141, stub_MyVideoView_onKeyDown_141 },
    { 142, stub_MyVideoView_onKeyLongPress_142 },
    { 144, stub_MyVideoView_onTouchEvent_144 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 5, stub_GLBluetooth_getDisplayName_5 },
    { 11, stub_GLBluetooth_getReceiveData_11 },
    { 12, stub_GLBluetoothService_GLBluetoothService_12 },
    { 22, stub_GLBluetoothService_getDisplayName_22 },
    { 28, stub_GLBluetoothService_getReceiveData_28 },
    { 37, stub_GLMediaPlayer_getSoundFile_37 },
    { 77, stub_GLResLoader_getResourceFull_77 },
    { 78, stub_GLResLoader_getResourceFull_78 },
    { 79, stub_GLResLoader_getRawResource_79 },
    { 80, stub_GLResLoader_getResourceBytes_80 },
    { 81, stub_GLResLoader_getString_81 },
    { 84, stub_GLResLoader_copyMovieFileFromAssetsToTMP_84 },
    { 86, stub_GLResLoader_getResourceRead_86 },
    { 90, stub_GameGLSurfaceView_GameGLSurfaceView_90 },
    { 94, stub_GameRenderer_GameRenderer_94 },
    { 130, stub_Gangster2_VZGetGamePrice_130 },
    { 131, stub_Gangster2_VZGetGameName_131 },
    { 132, stub_Gangster2_VZGetLastServerMsg_132 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 21, stub_GLBluetoothService_convertMacAddressToInteger_21 },
    { 33, stub_GLMediaPlayer_isSoundLoaded_33 },
    { 34, stub_GLMediaPlayer_isSoundLoadedBig_34 },
    { 43, stub_GLMediaPlayer_GetDeviceSoundType_43 },
    { 63, stub_GLMediaPlayer_loadMovie_63 },
    { 68, stub_GLMediaPlayer_isMediaPlaying_68 },
    { 71, stub_GLMediaPlayer_detectPhoneLang_71 },
    { 73, stub_GLMediaPlayer_getDeviceWidth_73 },
    { 74, stub_GLMediaPlayer_GetDeviceType_74 },
    { 76, stub_GLResLoader_getResourceLength_76 },
    { 82, stub_GLResLoader_getResourceOpen_82 },
    { 83, stub_GLResLoader_copyResourceFromAssets_83 },
    { 85, stub_GLResLoader_getResourceLength2_85 },
    { 88, stub_GLResLoader_getResourceSkip_88 },
    { 113, stub_Gangster2_isWifiAlive_113 },
    { 114, stub_Gangster2_unlockDemo_114 },
    { 117, stub_Gangster2_DisableLaunchGame_117 },
    { 125, stub_Gangster2_VZIsMobileNetworkReady_125 },
    { 128, stub_Gangster2_VZIsInProgress_128 },
    { 129, stub_Gangster2_VZIsErrorOcurred_129 },
};

// Candidate methodsByte[] entries -- append into the real methodsByte[] in java.c
static const MethodsByte generated_methodsByte[] = {
    { 87, stub_GLResLoader_getResourceReadByte_87 },
};

