/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth ----
void stub_GLBluetooth_init_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.init(LContext;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jboolean stub_GLBluetooth_isSupported_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.isSupported()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_GLBluetooth_isAvailable_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.isAvailable()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GLBluetooth_setAvailable_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.setAvailable(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

jboolean stub_GLBluetooth_create_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.create(Ljava/lang/String;I)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    return JNI_FALSE;
}

jbyteArray stub_GLBluetooth_getDisplayName_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.getDisplayName(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_GLBluetooth_destroy_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.destroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLBluetooth_connect_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.connect(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLBluetooth_send_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.send(I[B)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
}

jboolean stub_GLBluetooth_acceptConnection_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.acceptConnection(I)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return JNI_FALSE;
}

void stub_GLBluetooth_denyConnection_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.denyConnection(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jbyteArray stub_GLBluetooth_getReceiveData_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetooth.getReceiveData()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService ----
jobject stub_GLBluetoothService_GLBluetoothService_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.GLBluetoothService(LUUID;Ljava/lang/String;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
    return NULL;
}

void stub_GLBluetoothService_Update_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.Update()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GLBluetoothService_startListen_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.startListen()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GLBluetoothService_enableDiscovery_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.enableDiscovery()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GLBluetoothService_startDiscovery_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.startDiscovery()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GLBluetoothService_stopDiscovery_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.stopDiscovery()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLBluetoothService_close_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.close()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLBluetoothService_connect_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.connect(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLBluetoothService_send_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.send(I[B)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
}

jint stub_GLBluetoothService_convertMacAddressToInteger_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.convertMacAddressToInteger(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jbyteArray stub_GLBluetoothService_getDisplayName_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.getDisplayName(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_GLBluetoothService_connectionFailed_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.connectionFailed()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLBluetoothService_connectionLost_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.connectionLost()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLBluetoothService_connected_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.connected(LBluetoothSocket;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GLBluetoothService_acceptConnection_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.acceptConnection(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLBluetoothService_denyConnection_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.denyConnection(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jbyteArray stub_GLBluetoothService_getReceiveData_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.getReceiveData()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_GLBluetoothService_parseIncommingData_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLBluetoothService.parseIncommingData()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer ----
void stub_GLMediaPlayer_init_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_restoreMasterVolume_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.restoreMasterVolume()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_init_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.init(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

jint stub_GLMediaPlayer_isSoundLoaded_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.isSoundLoaded(II)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isSoundLoadedBig_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.isSoundLoadedBig(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_loadSound_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.loadSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_loadSound_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.loadSound(IILContext;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jobject stub_GLMediaPlayer_getSoundFile_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.getSoundFile(I)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_GLMediaPlayer_loadSoundBig_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.loadSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_loadSoundBig_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.loadSoundBig(ILContext;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GLMediaPlayer_playSound_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.playSound(IIFF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
    jfloat arg3 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_releaseIdleMediaPlayers_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.releaseIdleMediaPlayers()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_playSoundBig_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.playSoundBig(IFI)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
    jint arg2 = (jint) va_arg(args, int);
}

jint stub_GLMediaPlayer_GetDeviceSoundType_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.GetDeviceSoundType()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_GLMediaPlayer_pauseSound_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.pauseSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseSoundBig_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.pauseSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSound_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.resumeSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSoundBig_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.resumeSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSound_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSoundForce_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopSoundForce(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSoundBig_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSound_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.unloadSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSoundBig_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.unloadSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setVolume_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setVolume(IIF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_setVolumeBig_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setVolumeBig(IF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_resetSound_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.resetSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setPitch_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setPitch(IIF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_stopAllSounds_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopAllPool_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopAllPool(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopAllBig_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.stopAllBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseAllSounds_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.pauseAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_resumeAllSounds_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.resumeAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_destroySoundPool_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.destroySoundPool()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLMediaPlayer_loadMovie_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.loadMovie(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

void stub_GLMediaPlayer_ResumeMovie_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.ResumeMovie()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_setMusicGain_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setMusicGain(F)V called -- fill in from the real Java impl (jadx).");
    jfloat arg0 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_setSfxGain_66(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setSfxGain(F)V called -- fill in from the real Java impl (jadx).");
    jfloat arg0 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_setVfxGain_67(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.setVfxGain(F)V called -- fill in from the real Java impl (jadx).");
    jfloat arg0 = (jfloat) va_arg(args, double);
}

jint stub_GLMediaPlayer_isMediaPlaying_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.isMediaPlaying(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_releaseSoundPool_69(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.releaseSoundPool()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_initSoundPoolArray_70(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.initSoundPoolArray()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLMediaPlayer_detectPhoneLang_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.detectPhoneLang()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_GLMediaPlayer_BlockSounds_72(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.BlockSounds(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

jint stub_GLMediaPlayer_getDeviceWidth_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.getDeviceWidth()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_GLMediaPlayer_GetDeviceType_74(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLMediaPlayer.GetDeviceType()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader ----
void stub_GLResLoader_init_75(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.init()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLResLoader_getResourceLength_76(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceLength(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jbyteArray stub_GLResLoader_getResourceFull_77(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceFull(Ljava/lang/String;)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_78(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceFull(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getRawResource_79(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getRawResource(ILContext;)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceBytes_80(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceBytes(Ljava/lang/String;II)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    return NULL;
}

jobject stub_GLResLoader_getString_81(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getString(ILContext;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jint stub_GLResLoader_getResourceOpen_82(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceOpen(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jint stub_GLResLoader_copyResourceFromAssets_83(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.copyResourceFromAssets(Ljava/lang/String;Ljava/lang/String;Z)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jboolean arg2 = (jboolean) va_arg(args, int);
    return 0;
}

jobject stub_GLResLoader_copyMovieFileFromAssetsToTMP_84(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.copyMovieFileFromAssetsToTMP(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jint stub_GLResLoader_getResourceLength2_85(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceLength2()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_GLResLoader_getResourceRead_86(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceRead(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyte stub_GLResLoader_getResourceReadByte_87(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceReadByte()B called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_GLResLoader_getResourceSkip_88(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceSkip(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLResLoader_getResourceClose_89(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GLResLoader.getResourceClose()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView ----
jobject stub_GameGLSurfaceView_GameGLSurfaceView_90(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView.GameGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameGLSurfaceView_onWindowFocusChanged_91(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_GameGLSurfaceView_onSizeChanged_92(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

jboolean stub_GameGLSurfaceView_onTouchEvent_93(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfaceView.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer ----
jobject stub_GameRenderer_GameRenderer_94(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer.GameRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameRenderer_onSurfaceCreated_95(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameRenderer_onSurfaceChanged_96(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GameRenderer_onDrawFrame_97(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.GameRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2 ----
void stub_Gangster2_onCreate_98(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Gangster2_loadConfig_99(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.loadConfig()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onPause_100(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onResume_101(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onStop_102(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onDestroy_103(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Gangster2_isDemo_104(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.isDemo()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_Gangster2_onRestart_105(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onStart_106(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onStart()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Gangster2_onTrackballEvent_107(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onTrackballEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Gangster2_onKeyDown_108(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Gangster2_onKeyUp_109(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_Gangster2_sendAppToBackground_110(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_Exit_111(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.Exit()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_onActivityResult_112(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jint stub_Gangster2_isWifiAlive_113(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.isWifiAlive()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_Gangster2_unlockDemo_114(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.unlockDemo()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_Gangster2_lockDemo_115(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.lockDemo()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_IncreaseLaunchTimes_116(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.IncreaseLaunchTimes()V called -- fill in from the real Java impl (jadx).");
}

jint stub_Gangster2_DisableLaunchGame_117(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.DisableLaunchGame()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_Gangster2_openBrowser_118(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.openBrowser(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Gangster2_OpenGLive_119(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.OpenGLive(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Gangster2_NotifyTrophy_120(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.NotifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Gangster2_readFromFile_121(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.readFromFile()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_initialize_Trophy_122(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.initialize_Trophy([I)V called -- fill in from the real Java impl (jadx).");
    jintArray arg0 = (jintArray) va_arg(args, jobject);
}

void stub_Gangster2_VZRestoreNetworkState_123(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZRestoreNetworkState()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_VZInitMobileNetwork_124(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZInitMobileNetwork()V called -- fill in from the real Java impl (jadx).");
}

jint stub_Gangster2_VZIsMobileNetworkReady_125(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZIsMobileNetworkReady()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_Gangster2_VZRequestLogin_126(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZRequestLogin()V called -- fill in from the real Java impl (jadx).");
}

void stub_Gangster2_VZRequestPurchaseGame_127(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZRequestPurchaseGame()V called -- fill in from the real Java impl (jadx).");
}

jint stub_Gangster2_VZIsInProgress_128(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZIsInProgress()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_Gangster2_VZIsErrorOcurred_129(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZIsErrorOcurred()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_Gangster2_VZGetGamePrice_130(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZGetGamePrice()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Gangster2_VZGetGameName_131(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZGetGameName()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Gangster2_VZGetLastServerMsg_132(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.VZGetLastServerMsg()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Gangster2_onSensorChanged_133(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onSensorChanged(LSensorEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Gangster2_onAccuracyChanged_134(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.Gangster2.onAccuracyChanged(LSensor;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

// ---- com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView ----
void stub_MyVideoView_onCreate_135(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_MyVideoView_onPause_136(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_MyVideoView_onStop_137(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_MyVideoView_onWindowFocusChanged_138(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_MyVideoView_sendAppToBackground_139(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_MyVideoView_onKeyUp_140(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_MyVideoView_onKeyDown_141(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_MyVideoView_onKeyLongPress_142(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onKeyLongPress(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_MyVideoView_playVideo_143(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.playVideo()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_MyVideoView_onTouchEvent_144(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_MyVideoView_HideButton_145(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.HideButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_MyVideoView_ShowButton_146(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.TBFV.GloftGMHP.ML.MyVideoView.ShowButton()V called -- fill in from the real Java impl (jadx).");
}

